name: Deploy Python Azure Function (remote build with Core Tools)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'trendmicro-oat-events-ingest2' # Azure Function App name
  PYTHON_VERSION: '3.12'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo content
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python (mainly if I want to run tests before publishing)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # (Optional) run tests locally on CI before deploying
      # - name: Run tests
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      #     pytest

      # Install Azure Functions Core Tools (needed to use `func azure functionapp publish`)
      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      # Deploy to Azure Function App using remote build (Oryx will install my dependencies from requirements.txt on Azure)
      - name: Publish to Azure Function App
        run: |
          func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --python \
            --build remote \
            --publish-profile "${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}"
