name: Deploy Python Azure Function (remote build)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.12'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (Opcional) pruebas, lint, etc. SIN instalar a sistema. 
      # Si necesitas deps para tests, usa un venv y NO lo empaquetes.

      - name: Deploy to Azure Functions (Oryx remote build)
        uses: Azure/functions-action@v1
        with:
          app-name: 'trendmicro-oat-events-ingest2'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D5E946ECB1B9405B8169FC389BC25C70 }}
