name: Deploy Python Azure Function (Publish Profile + Remote Build)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'trendmicro-oat-events-ingest2' # Your Function App name
  PYTHON_VERSION: '3.12'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python (useful if I want to run tests before deploy)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # (Optional) run tests locally in CI
      # - name: Run tests
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      #     pytest

      # Install Azure Functions Core Tools (needed for func publish)
      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      # Save publish profile from GitHub secret into a file
      - name: Write publish profile to file
        run: echo "${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D5E946ECB1B9405B8169FC389BC25C70 }}" > publishProfile.publishsettings

      # Deploy with remote build (Oryx installs requirements.txt on Azure)
      - name: Publish to Azure Function App
        run: |
          func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --python \
            --build remote \
            --publish-profile publishProfile.publishsettings

      # Cleanup for security
      - name: Cleanup
        run: rm publishProfile.publishsettings
