name: Deploy Python Azure Function (self-contained package)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'trendmicro-oat-events-ingest2' # Function App name
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo content
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Install dependencies into .python_packages (this is where Azure Functions looks)
      - name: Install dependencies into .python_packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .python_packages/lib/site-packages
          python -m compileall .

      # Zip everything (code + .python_packages + manifest files)
      - name: Create deployment package
        run: |
          zip -r release.zip * .python_packages \
            -x "*/.git/*" \
            -x "*/__pycache__/*" \
            -x "*/venv/*"

      # Upload the zip to Azure using publish profile
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: release.zip
          publish-profile: ${{ secrets.PRSG_PUBLISHPROFILE }}
